### ISSUE TITLE
collab server bundle module not found

### ISSUE THREAD

**Issue by tedchou12** [MO-Movia/licit#1]
Thank you so much! This is wonderful. Thank you for maintaining it.

Sorry, I am quite unexperienced with node js.
I wish to get the collaborations module working. I have already got webserver okay. But the collab server cannot run properly:
```
ted.chou@IITPC20-0109 prosemirror12 % python run_collab_server.py 
================================================================================
PORT=3002 IP=192.168.1.2 node servers/collab/run_licit_collab_server.bundle.js
================================================================================
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module '/Applications/MAMP/htdocs/prosemirror12/servers/collab/run_licit_collab_server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```
Could you guide me?
Thank you!.

**Comment by tedchou12** [comment]
I found out that there is no `/servers/collab/run_licit_collab_server.bundle.js` file. I tried to run `npm build:dist` `npm build:ilicit` but none generates the servers folder, anyone could guide me on that?

So I tried to get into `ilicit/server/collab` and execute:
`node start.js`
but ended with:
````
ted.chou@IITPC20-0109 collab % node start.js         
file:///Applications/MAMP/htdocs/prosemirror12/licit/server/collab/server.js:21
function handleCollabRequest(req: any, resp: any) {
                                ^

SyntaxError: Unexpected token ':'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:117:18)
````

I am puzzled... seems like the syntax is itself an error?

**Comment by firmusoft** [comment]
@tedchou12 ,

Recent changes related to fonts did have a fonts reference in the collab server, which did cause this issue. Now this has been fixed and shall be moved to main branch very soon.

**Comment by tedchou12** [comment]
Thank you so much! I have generated the /servers folder with the new branch.
