### ISSUE TITLE
How to reconcile steps to make the whole doc json?

### ISSUE THREAD

**Issue by tedchou12** [MO-Movia/licit#3]
Sorry for asking so many questions.
Since my servers are mostly running on Apache PHP. I wish to handle post/get requests on PHP, I also have my databases accesses on PHP, launching a new Node JS server means I have to launch another server (cost) as well as extra management.

I have actually got some successes with: https://github.com/tedchou12/prosemirror-server-php. Thanks to the collab server that is working, is a great example for me to follow through.

However, I got a lot of delta steps request:

````
...
{"version":308,"steps":[{"stepType":"replace","from":14,"to":14,"slice":{"content":[{"type":"text","marks":[{"type":"super"}],"text":"f"}]}}],"clientID":"827fec50-fca0-11ea-9678-71616149d424"}
{"version":309,"steps":[{"stepType":"replace","from":15,"to":15,"slice":{"content":[{"type":"text","marks":[{"type":"super"}],"text":"a"}]}}],"clientID":"827fec50-fca0-11ea-9678-71616149d424"}
{"version":310,"steps":[{"stepType":"addMark","mark":{"type":"mark-font-size","attrs":{"pt":14}},"from":1,"to":5}],"clientID":"827fec50-fca0-11ea-9678-71616149d424"}
````

When I reload the document, it will load up all the changes again, I wonder how I can convert the history steps and reconcile to a new document?
I took a look in the collab server `licit/server/collab/server.js`, but with minimum success. I think the magic is probably done in `prosemirror-model`, could anyone point me in the right direction?

Thank you so much!

**Comment by MO-Movia** [comment]
Glad you like working with it.

Yes, Prosemirror is very transaction oriented. It “journals” all the changes internally, but that is what flies back and forth with the collaboration server.  Prosemirror has a lot of information available on how it works, the model, etc. on its website. We are maintaining the plugins that add all the features outside of the editor (as you can see, Prosemirror is very basic, all the features of the editor are made via plugins).

Main website: https://prosemirror.net/
Documentation (extensive): https://prosemirror.net/docs/

A couple of blog entries about the concept<http://marijnhaverbeke.nl/blog/prosemirror.html> of Prosemirror and the collaborative editing<http://marijnhaverbeke.nl/blog/collaborative-editing.html> technique.

Finally, search on the forum – many people of had some issues understanding the way it works, and there is a lot of discussion in there on the design patterns and how best to handle what you are trying to accomplish.

https://discuss.prosemirror.net/

I believe I’ve read specifically about the history, and the best way to clean that up.

Hope this helps!

**Comment by MO-Movia** [comment]
I see that it looks like you have already found the forum!  Hopefully, someone will bounce in and give you some direction!

From: Mike Gilger
Sent: Tuesday, September 22, 2020 8:30 AM
To: MO-Movia/licit <reply@reply.github.com>
Cc: modus@firmusoft.co.in
Subject: RE: [MO-Movia/licit] How to reconcile steps to make the whole doc json? (#3)

Glad you like working with it.

Yes, Prosemirror is very transaction oriented. It “journals” all the changes internally, but that is what flies back and forth with the collaboration server.  Prosemirror has a lot of information available on how it works, the model, etc. on its website. We are maintaining the plugins that add all the features outside of the editor (as you can see, Prosemirror is very basic, all the features of the editor are made via plugins).

Main website: https://prosemirror.net/
Documentation (extensive): https://prosemirror.net/docs/

A couple of blog entries about the concept<http://marijnhaverbeke.nl/blog/prosemirror.html> of Prosemirror and the collaborative editing<http://marijnhaverbeke.nl/blog/collaborative-editing.html> technique.

Finally, search on the forum – many people of had some issues understanding the way it works, and there is a lot of discussion in there on the design patterns and how best to handle what you are trying to accomplish.

https://discuss.prosemirror.net/

I believe I’ve read specifically about the history, and the best way to clean that up.

Hope this helps!

**Comment by tedchou12** [comment]
Thank you so much for all the info.
I was able to get it working yes!
```
// import { Step } from 'prosemirror-transform'
// import { Schema } from 'prosemirror-model'
// import { schema } from 'prosemirror-schema-basic'
// import { readFileSync, writeFile } from 'fs'


const { Schema } = require('prosemirror-model')
const { schema } = require('prosemirror-schema-basic')
const { Step } = require('prosemirror-transform')
const { readFileSync, writeFile } = require('fs')


doc_json = readFileSync('data/doc.txt', () => { null })
doc_json = JSON.parse(doc_json)

// read the initial document (or have it somewhere)
// var doc_node = Node.fromJSON(schema, doc_json);
var doc_node = schema.nodeFromJSON(doc_json)

step_jsons = readFileSync('data/step.txt', () => { null })
step_jsons = step_jsons.toString().split('\n').filter(Boolean)

for (var step_json of step_jsons) {
  step_json = JSON.parse(step_json)
  for (var step of step_json['steps']) {
    var step = Step.fromJSON(schema, step)
    var result = step.apply(doc_node)
    if (result.failed) {

    } else {
      doc_node = result.doc
      console.log(doc_node.toJSON())
    }
  }
}

console.log(doc_node)
```

I have very little experience with node js, but it's quite fun to learn it.
