### ISSUE TITLE
Inherit marks in new bullet point

### ISSUE THREAD

**Issue by amilich** [MO-Movia/licit#41]
Any way to inherit the previous bullet's marks in a new one? I've tried a few messy things, like getting the marks of the text node in the previous bullet and dispatching a tr to set them for the next one, but I'd hope there is a better way.

**Comment by Seybi-ea** [comment]
Sorry we didnt faced the above scenario in our application development, Shall look into it once we get a chance, BTW
you can check the below usefull links, hope this helps 

https://prosemirror.net/
https://prosemirror.net/docs/
Discussion forumn - https://discuss.prosemirror.net/

**Comment by amilich** [comment]
Got it, thank you
