### ISSUE TITLE
Bottleneck and crash on large deletes [retested and not a problem!]

### ISSUE THREAD

**Issue by Xyloboard** [MO-Movia/licit#64]
Note - I've retested this and cannot replicate! - so must have been something awry with my machine/state. Please close - sorry!

--

If you paste in a HUGE document (example attached), the paste works quickly (a second or two), but if you then try to select most of it and hit delete, the interface locks up and the browser crashes (tested in latest chrome). This behaviour is not seen on the reference basic implementation of Prose Mirror - here: [https://prosemirror.net/examples/basic/](https://prosemirror.net/examples/basic/) so it must be something within this implementation that's causing the problem.
[Example huge document.txt](https://github.com/MO-Movia/licit/files/5942735/Example.huge.document.txt)

I accept that this is larger than most requirements (the example is war and peace), but equally, it does work in prose mirror and it would be amazing for this project to work fine with really large files too!

**Comment by melgish** [comment]
Thanks for letting us know..
